/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/VR Building 01.glb --types --transform 
Files: public/models/VR Building 01.glb [1.02MB] > /home/zennomi/hust/minaverse/models/VR Building 01.glb [76.03KB] (93%)
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_23: THREE.Mesh
    Object_26: THREE.Mesh
    Object_6: THREE.Mesh
    Object_9: THREE.Mesh
    Object_17: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
    PaletteMaterial003: THREE.MeshStandardMaterial
    PaletteMaterial004: THREE.MeshStandardMaterial
    PaletteMaterial005: THREE.MeshPhysicalMaterial
  }
}

export function CarBuilding(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/VR Building 01.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_23.geometry} material={materials.PaletteMaterial001} position={[-84.508, 0, 11.47]} rotation={[-Math.PI / 2, 0, 0]} scale={0.1} />
      <mesh geometry={nodes.Object_26.geometry} material={materials.PaletteMaterial002} position={[-84.508, 0, 11.47]} rotation={[-Math.PI / 2, 0, 0]} scale={0.1} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.PaletteMaterial003} position={[-84.508, 0, 11.47]} rotation={[-Math.PI / 2, 0, 0]} scale={0.1} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.PaletteMaterial004} position={[-84.508, 0, 11.47]} rotation={[-Math.PI / 2, 0, 0]} scale={0.1} />
      <mesh geometry={nodes.Object_17.geometry} material={materials.PaletteMaterial005} position={[-84.508, 0, 11.47]} rotation={[-Math.PI / 2, 0, 0]} scale={0.1} />
    </group>
  )
}

useGLTF.preload('/models/VR Building 01.glb')
