/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: ChristyHsu (https://sketchfab.com/ida61xq)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/white-round-exhibition-gallery-a443b8a0a2314a55ae5dee4dd6a151a0
Title: White round exhibition gallery
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { RigidBody } from '@react-three/rapier'

type GLTFResult = GLTF & {
    nodes: {
        Cylinder__0: THREE.Mesh
        Cylinder003__0: THREE.Mesh
        Cylinder004__0: THREE.Mesh
        Cylinder005__0: THREE.Mesh
        Cylinder006__0: THREE.Mesh
        Torus011__0: THREE.Mesh
        Cylinder014_Material001_0: THREE.Mesh
        Cylinder015__0: THREE.Mesh
        Cylinder007_Material002_0: THREE.Mesh
        Cylinder008_Material002_0: THREE.Mesh
        Cylinder009_Material002_0: THREE.Mesh
        Cylinder010_Material002_0: THREE.Mesh
        Cylinder001__0: THREE.Mesh
        Cylinder012_Material004_0: THREE.Mesh
        Cylinder013__0: THREE.Mesh
        Cylinder016_Material009_0: THREE.Mesh
    }
    materials: {
        Cylinder__0: THREE.MeshStandardMaterial
        ['Material.001']: THREE.MeshStandardMaterial
        ['Material.002']: THREE.MeshStandardMaterial
        ['Material.004']: THREE.MeshStandardMaterial
        ['Material.009']: THREE.MeshStandardMaterial
    }
}

export function Exhibition(props: JSX.IntrinsicElements['group']) {
    const { nodes, materials } = useGLTF('/white_round_exhibition_gallery.glb') as GLTFResult
    return (
        <RigidBody mass={1} type="fixed" position={[0, 3, 0]} scale={[0.4, 0.4, 0.4]} colliders={"trimesh"}>
            <group {...props} dispose={null}>
                <group scale={0.01}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder__0.geometry}
                        material={materials.Cylinder__0}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[1327.45, 1327.45, 501.949]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder003__0.geometry}
                        material={materials.Cylinder__0}
                        position={[0, 46.149, 0]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[1327.45, 1327.45, 501.949]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder004__0.geometry}
                        material={materials.Cylinder__0}
                        position={[0, 343.929, 0]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[1940.379, 1940.379, 733.716]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder005__0.geometry}
                        material={materials.Cylinder__0}
                        position={[0, 463.774, 0]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[2630.109, 2630.109, 786.067]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder006__0.geometry}
                        material={materials.Cylinder__0}
                        position={[0, 417.743, 0]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[3366.385, 3366.385, 676.562]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Torus011__0.geometry}
                        material={materials.Cylinder__0}
                        position={[0, 929.591, 0]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[-1351.922, 1351.922, 1351.922]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder014_Material001_0.geometry}
                        material={materials['Material.001']}
                        position={[0, 444.248, 0]}
                        rotation={[Math.PI / 2, 0, -Math.PI]}
                        scale={[-2140.547, 2140.547, 41.441]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder015__0.geometry}
                        material={materials.Cylinder__0}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[1327.45, 1327.45, 501.949]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder007_Material002_0.geometry}
                        material={materials['Material.002']}
                        position={[0, -491.111, 0]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[1664.058, 1664.058, 181.851]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder008_Material002_0.geometry}
                        material={materials['Material.002']}
                        position={[0, -430.178, 0]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[2429.868, 2429.868, 103.57]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder009_Material002_0.geometry}
                        material={materials['Material.002']}
                        position={[0, -365.182, 0]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[3246.547, 3246.547, 103.57]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder010_Material002_0.geometry}
                        material={materials['Material.002']}
                        position={[0, -296.993, 0]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[4105.58, 4105.58, 103.57]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder001__0.geometry}
                        material={materials.Cylinder__0}
                        position={[0, -213.755, 0]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[2287.581, 2287.581, 661.655]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder012_Material004_0.geometry}
                        material={materials['Material.004']}
                        position={[0, -213.755, 0]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[2287.581, 2287.581, 661.655]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder013__0.geometry}
                        material={materials.Cylinder__0}
                        position={[0, -213.755, 0]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[2287.581, 2287.581, 661.655]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder016_Material009_0.geometry}
                        material={materials['Material.009']}
                        position={[0, 691.037, 0]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[-998.133, 998.133, 73.472]}
                    />
                </group>
            </group>
        </RigidBody>
    )
}

useGLTF.preload('/white_round_exhibition_gallery.glb')
