/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/vr-art-gallery-2020-l-baked-max-scene.glb --types --transform 
Files: public/models/vr-art-gallery-2020-l-baked-max-scene.glb [73.58MB] > /home/zennomi/hust/minaverse/vr-art-gallery-2020-l-baked-max-scene-transformed.glb [456.27KB] (99%)
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    about_about_0: THREE.Mesh
    glass_glass_0: THREE.Mesh
    windows_windows_0: THREE.Mesh
    paintings_paintings_0: THREE.Mesh
    post_post_0: THREE.Mesh
    ceiling_ceiling_0: THREE.Mesh
    walls_walls_0: THREE.Mesh
    floor_floor_0: THREE.Mesh
  }
  materials: {
    about: THREE.MeshStandardMaterial
    glass: THREE.MeshStandardMaterial
    windows: THREE.MeshStandardMaterial
    paintings: THREE.MeshStandardMaterial
    post: THREE.MeshStandardMaterial
    ceiling: THREE.MeshStandardMaterial
    walls: THREE.MeshStandardMaterial
    floor: THREE.MeshStandardMaterial
  }
}

export function Gallery(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/vr-art-gallery-2020-l-baked-max-scene.glb') as GLTFResult
  materials.floor.polygonOffset = true
  materials.floor.polygonOffsetFactor = -1
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.about_about_0.geometry} material={materials.about} />
      <mesh geometry={nodes.glass_glass_0.geometry} material={materials.glass} />
      <mesh geometry={nodes.windows_windows_0.geometry} material={materials.windows} />
      <mesh geometry={nodes.paintings_paintings_0.geometry} material={materials.paintings} />
      <mesh geometry={nodes.post_post_0.geometry} material={materials.post} />
      <mesh geometry={nodes.ceiling_ceiling_0.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.walls_walls_0.geometry} material={materials.walls} />
      <mesh geometry={nodes.floor_floor_0.geometry} material={materials.floor} />
    </group>
  )
}

useGLTF.preload('/models/vr-art-gallery-2020-l-baked-max-scene.glb')
