/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/kaori__dance_with_violin.glb --types 
Author: lidas (https://sketchfab.com/lidas)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/kaori-dance-with-violin-e9edc974e5814aab8c81f6ac66786df9
Title: Kaori  dance with violin
*/

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_23: THREE.Mesh
    Object_33: THREE.Mesh
    Object_7: THREE.SkinnedMesh
    Object_9: THREE.SkinnedMesh
    Object_10: THREE.SkinnedMesh
    GLTF_created_0_rootJoint: THREE.Bone
  }
  materials: {
    DefaultMaterial: THREE.MeshStandardMaterial
    Hair: THREE.MeshStandardMaterial
    Blego_Brick_Yellow: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ActionName = 'Dance'
interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}
type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh'] | JSX.IntrinsicElements['skinnedMesh'] | JSX.IntrinsicElements['bone']>>

export function Kaori(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/kaori__dance_with_violin.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    actions.Dance?.play()
  }, [])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Armature_37" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <group name="04_35" />
                  <group name="skeleton_36" />
                  <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.Hair} skeleton={nodes.Object_7.skeleton} />
                  <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.Blego_Brick_Yellow} skeleton={nodes.Object_9.skeleton} />
                  <skinnedMesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.Blego_Brick_Yellow} skeleton={nodes.Object_10.skeleton} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/kaori__dance_with_violin.glb')
