/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/human-sleep-module-lab.glb --types --transform 
Files: public/models/human-sleep-module-lab.glb [26.43MB] > /home/zennomi/hust/minaverse/models/human-sleep-module-lab.glb [3.36MB] (87%)
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Material2: THREE.Mesh
    Material2003: THREE.Mesh
    Material2012: THREE.Mesh
    Material2022: THREE.Mesh
    Material2039: THREE.Mesh
    Material2042: THREE.Mesh
    Material2044: THREE.Mesh
    Material2045: THREE.Mesh
    Material2047: THREE.Mesh
    Material2048: THREE.Mesh
    Material2050: THREE.Mesh
    Material3: THREE.Mesh
    Material3001: THREE.Mesh
    Material3002: THREE.Mesh
    Material3006: THREE.Mesh
    Material3007: THREE.Mesh
    Material3008: THREE.Mesh
    Material3009: THREE.Mesh
    Material3021: THREE.Mesh
    Material3025: THREE.Mesh
  }
  materials: {
    material_6: THREE.MeshStandardMaterial
    PaletteMaterial001: THREE.MeshStandardMaterial
    material_6_1: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshPhysicalMaterial
    PaletteMaterial003: THREE.MeshStandardMaterial
    ['ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½_0']: THREE.MeshStandardMaterial
    PaletteMaterial004: THREE.MeshStandardMaterial
    material_2_3: THREE.MeshStandardMaterial
    material_4_5: THREE.MeshStandardMaterial
    material_6_7: THREE.MeshStandardMaterial
    PaletteMaterial005: THREE.MeshStandardMaterial
    material_3: THREE.MeshStandardMaterial
    material_2: THREE.MeshStandardMaterial
    __: THREE.MeshStandardMaterial
    material_1: THREE.MeshStandardMaterial
    material_5: THREE.MeshStandardMaterial
    material_4: THREE.MeshStandardMaterial
    ['ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½_Material']: THREE.MeshStandardMaterial
    Color_002: THREE.MeshStandardMaterial
    material_8: THREE.MeshStandardMaterial
  }
}

export function Lab(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/human-sleep-module-lab.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Material2.geometry} material={materials.material_6} position={[-479.787, 0, 500]} rotation={[-1.585, 0, -0.007]} />
      <mesh geometry={nodes.Material2003.geometry} material={materials.PaletteMaterial001} position={[-479.787, 0, 500]} rotation={[-1.585, 0, -0.007]} />
      <mesh geometry={nodes.Material2012.geometry} material={materials.material_6_1} position={[-479.787, 0, 500]} rotation={[-1.585, 0, -0.007]} />
      <mesh geometry={nodes.Material2022.geometry} material={materials.PaletteMaterial002} position={[-479.787, 0, 500]} rotation={[-1.585, 0, -0.007]} />
      <mesh geometry={nodes.Material2039.geometry} material={materials.PaletteMaterial003} position={[-479.787, 0, 500]} rotation={[-1.585, 0, -0.007]} />
      <mesh geometry={nodes.Material2042.geometry} material={materials['ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½_0']} position={[-479.787, 0, 500]} rotation={[-1.585, 0, -0.007]} />
      <mesh geometry={nodes.Material2044.geometry} material={materials.PaletteMaterial004} position={[-479.787, 0, 500]} rotation={[-1.585, 0, -0.007]} />
      <mesh geometry={nodes.Material2045.geometry} material={materials.material_2_3} position={[-479.787, 0, 500]} rotation={[-1.585, 0, -0.007]} />
      <mesh geometry={nodes.Material2047.geometry} material={materials.material_4_5} position={[-479.787, 0, 500]} rotation={[-1.585, 0, -0.007]} />
      <mesh geometry={nodes.Material2048.geometry} material={materials.material_6_7} position={[-479.787, 0, 500]} rotation={[-1.585, 0, -0.007]} />
      <mesh geometry={nodes.Material2050.geometry} material={materials.PaletteMaterial005} position={[-479.787, 0, 500]} rotation={[-1.585, 0, -0.007]} />
      <mesh geometry={nodes.Material3.geometry} material={materials.material_3} position={[-479.787, 0, 500]} rotation={[-1.585, 0, -0.007]} />
      <mesh geometry={nodes.Material3001.geometry} material={materials.material_2} position={[-479.787, 0, 500]} rotation={[-1.585, 0, -0.007]} />
      <mesh geometry={nodes.Material3002.geometry} material={materials.__} position={[-479.787, 0, 500]} rotation={[-1.585, 0, -0.007]} />
      <mesh geometry={nodes.Material3006.geometry} material={materials.material_1} position={[-479.787, 0, 500]} rotation={[-1.585, 0, -0.007]} />
      <mesh geometry={nodes.Material3007.geometry} material={materials.material_5} position={[-479.787, 0, 500]} rotation={[-1.585, 0, -0.007]} />
      <mesh geometry={nodes.Material3008.geometry} material={materials.material_4} position={[-479.787, 0, 500]} rotation={[-1.585, 0, -0.007]} />
      <mesh geometry={nodes.Material3009.geometry} material={materials['ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½_Material']} position={[-479.787, 0, 500]} rotation={[-1.585, 0, -0.007]} />
      <mesh geometry={nodes.Material3021.geometry} material={materials.Color_002} position={[-479.787, 0, 500]} rotation={[-1.585, 0, -0.007]} />
      <mesh geometry={nodes.Material3025.geometry} material={materials.material_8} position={[-479.787, 0, 500]} rotation={[-1.585, 0, -0.007]} />
    </group>
  )
}

useGLTF.preload('/models/human-sleep-module-lab.glb')
