/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/models/Scifi_Lab.glb --types 
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Center_Table_Scifi_Center_Table_mat_0: THREE.Mesh
    Floor_Scifi_Floor_mat_0: THREE.Mesh
    Roof_Scifi_Roof_mat_0: THREE.Mesh
    Bench10_Scifi_Bench_mat_0: THREE.Mesh
    Bench6_Scifi_Bench_mat_0: THREE.Mesh
    Bench7_Scifi_Bench_mat_0: THREE.Mesh
    Bench8_Scifi_Bench_mat_0: THREE.Mesh
    Bench9_Scifi_Bench_mat_0: THREE.Mesh
    Frame1_Scifi_Tunnel_Loop_M_0: THREE.Mesh
    Frame3_Scifi_Tunnel_Loop_M_0: THREE.Mesh
    Tunnel_door_L2_Scifi_Tunnel_Door_0: THREE.Mesh
    Tunnel_door_R2_Scifi_Tunnel_Door_0: THREE.Mesh
    Hollow1_Scifi_Tunnel_Loop_M_0: THREE.Mesh
    Hollow3_Scifi_Tunnel_Loop_M_0: THREE.Mesh
    Tunnel_Exit_L_Door_Scifi_Tunnel_Door_0: THREE.Mesh
    Tunnel_Exit_R_Door_Scifi_Tunnel_Door_0: THREE.Mesh
    Tunnel_Glass_L_Door_Scifi_Door_Glass_0: THREE.Mesh
    Tunnel_Glass_L_Door1_Scifi_Door_Glass_0: THREE.Mesh
    Tunnel_Glass_L_Door2_Scifi_Door_Glass_0: THREE.Mesh
    Tunnel_Glass_R_Door_Scifi_Door_Glass_0: THREE.Mesh
    Tunnel_Glass_R_Door1_Scifi_Door_Glass_0: THREE.Mesh
    Tunnel_Glass_R_Door2_Scifi_Door_Glass_0: THREE.Mesh
    Frame_Scifi_Tunnel_Loop_M_0: THREE.Mesh
    Hollow2_Scifi_Tunnel_Loop_M_0: THREE.Mesh
    Light2_Scifi_Tunnel_Loop_M_0: THREE.Mesh
    Light3_Scifi_Tunnel_Loop_M_0: THREE.Mesh
    Frame2_Scifi_Tunnel_Loop_M_0: THREE.Mesh
    Hollow_Scifi_Tunnel_Loop_M_0: THREE.Mesh
    Light_Scifi_Tunnel_Loop_M_0: THREE.Mesh
    Light1_Scifi_Tunnel_Loop_M_0: THREE.Mesh
    Frame4_Scifi_Tunnel_Loop_M_0: THREE.Mesh
    Hollow4_Scifi_Tunnel_Loop_M_0: THREE.Mesh
    Light4_Scifi_Tunnel_Loop_M_0: THREE.Mesh
    Light5_Scifi_Tunnel_Loop_M_0: THREE.Mesh
    Wall__Scifi_Wall_mat_0: THREE.Mesh
    Wall__Scifi_Window_Glass_0: THREE.Mesh
  }
  materials: {
    Scifi_Center_Table_mat: THREE.MeshStandardMaterial
    Scifi_Floor_mat: THREE.MeshStandardMaterial
    Scifi_Roof_mat: THREE.MeshStandardMaterial
    Scifi_Bench_mat: THREE.MeshStandardMaterial
    Scifi_Tunnel_Loop_M: THREE.MeshStandardMaterial
    Scifi_Tunnel_Door: THREE.MeshStandardMaterial
    Scifi_Door_Glass: THREE.MeshPhysicalMaterial
    Scifi_Wall_mat: THREE.MeshStandardMaterial
    Scifi_Window_Glass: THREE.MeshStandardMaterial
  }
}


export function ScifiLab(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/Scifi_Lab.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0.05, 0, -6.592]} rotation={[-1.569, 0, 0.016]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.Center_Table_Scifi_Center_Table_mat_0.geometry} material={materials.Scifi_Center_Table_mat} />
          <mesh geometry={nodes.Floor_Scifi_Floor_mat_0.geometry} material={materials.Scifi_Floor_mat} />
          <mesh geometry={nodes.Roof_Scifi_Roof_mat_0.geometry} material={materials.Scifi_Roof_mat} />
          <mesh geometry={nodes.Bench10_Scifi_Bench_mat_0.geometry} material={materials.Scifi_Bench_mat} rotation={[0, -1.265, 0]} />
          <mesh geometry={nodes.Bench6_Scifi_Bench_mat_0.geometry} material={materials.Scifi_Bench_mat} rotation={[-Math.PI, 0.654, -Math.PI]} />
          <mesh geometry={nodes.Bench7_Scifi_Bench_mat_0.geometry} material={materials.Scifi_Bench_mat} rotation={[Math.PI, -0.611, Math.PI]} />
          <mesh geometry={nodes.Bench8_Scifi_Bench_mat_0.geometry} material={materials.Scifi_Bench_mat} rotation={[0, 1.222, 0]} />
          <mesh geometry={nodes.Bench9_Scifi_Bench_mat_0.geometry} material={materials.Scifi_Bench_mat} />
          <mesh geometry={nodes.Frame1_Scifi_Tunnel_Loop_M_0.geometry} material={materials.Scifi_Tunnel_Loop_M} />
          <mesh geometry={nodes.Frame3_Scifi_Tunnel_Loop_M_0.geometry} material={materials.Scifi_Tunnel_Loop_M} />
          <mesh geometry={nodes.Tunnel_door_L2_Scifi_Tunnel_Door_0.geometry} material={materials.Scifi_Tunnel_Door} />
          <mesh geometry={nodes.Tunnel_door_R2_Scifi_Tunnel_Door_0.geometry} material={materials.Scifi_Tunnel_Door} />
          <mesh geometry={nodes.Hollow1_Scifi_Tunnel_Loop_M_0.geometry} material={materials.Scifi_Tunnel_Loop_M} />
          <mesh geometry={nodes.Hollow3_Scifi_Tunnel_Loop_M_0.geometry} material={materials.Scifi_Tunnel_Loop_M} />
          <mesh geometry={nodes.Tunnel_Exit_L_Door_Scifi_Tunnel_Door_0.geometry} material={materials.Scifi_Tunnel_Door} />
          <mesh geometry={nodes.Tunnel_Exit_R_Door_Scifi_Tunnel_Door_0.geometry} material={materials.Scifi_Tunnel_Door} />
          <mesh geometry={nodes.Tunnel_Glass_L_Door_Scifi_Door_Glass_0.geometry} material={materials.Scifi_Door_Glass} />
          <mesh geometry={nodes.Tunnel_Glass_L_Door1_Scifi_Door_Glass_0.geometry} material={materials.Scifi_Door_Glass} />
          <mesh geometry={nodes.Tunnel_Glass_L_Door2_Scifi_Door_Glass_0.geometry} material={materials.Scifi_Door_Glass} />
          <mesh geometry={nodes.Tunnel_Glass_R_Door_Scifi_Door_Glass_0.geometry} material={materials.Scifi_Door_Glass} />
          <mesh geometry={nodes.Tunnel_Glass_R_Door1_Scifi_Door_Glass_0.geometry} material={materials.Scifi_Door_Glass} />
          <mesh geometry={nodes.Tunnel_Glass_R_Door2_Scifi_Door_Glass_0.geometry} material={materials.Scifi_Door_Glass} />
          <mesh geometry={nodes.Frame_Scifi_Tunnel_Loop_M_0.geometry} material={materials.Scifi_Tunnel_Loop_M} />
          <mesh geometry={nodes.Hollow2_Scifi_Tunnel_Loop_M_0.geometry} material={materials.Scifi_Tunnel_Loop_M} />
          <mesh geometry={nodes.Light2_Scifi_Tunnel_Loop_M_0.geometry} material={materials.Scifi_Tunnel_Loop_M} />
          <mesh geometry={nodes.Light3_Scifi_Tunnel_Loop_M_0.geometry} material={materials.Scifi_Tunnel_Loop_M} />
          <mesh geometry={nodes.Frame2_Scifi_Tunnel_Loop_M_0.geometry} material={materials.Scifi_Tunnel_Loop_M} />
          <mesh geometry={nodes.Hollow_Scifi_Tunnel_Loop_M_0.geometry} material={materials.Scifi_Tunnel_Loop_M} />
          <mesh geometry={nodes.Light_Scifi_Tunnel_Loop_M_0.geometry} material={materials.Scifi_Tunnel_Loop_M} />
          <mesh geometry={nodes.Light1_Scifi_Tunnel_Loop_M_0.geometry} material={materials.Scifi_Tunnel_Loop_M} />
          <mesh geometry={nodes.Frame4_Scifi_Tunnel_Loop_M_0.geometry} material={materials.Scifi_Tunnel_Loop_M} />
          <mesh geometry={nodes.Hollow4_Scifi_Tunnel_Loop_M_0.geometry} material={materials.Scifi_Tunnel_Loop_M} />
          <mesh geometry={nodes.Light4_Scifi_Tunnel_Loop_M_0.geometry} material={materials.Scifi_Tunnel_Loop_M} />
          <mesh geometry={nodes.Light5_Scifi_Tunnel_Loop_M_0.geometry} material={materials.Scifi_Tunnel_Loop_M} />
          <mesh geometry={nodes.Wall__Scifi_Wall_mat_0.geometry} material={materials.Scifi_Wall_mat} />
          <mesh geometry={nodes.Wall__Scifi_Window_Glass_0.geometry} material={materials.Scifi_Window_Glass} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Scifi_Lab.glb')
