/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/sci-fi-interior-gallery-10.glb --types --transform 
Files: public/models/sci-fi-interior-gallery-10.glb [17.19MB] > /home/zennomi/hust/minaverse/sci-fi-interior-gallery-10-transformed.glb [894.18KB] (95%)
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ScreenFrame_ScreenFrame_0: THREE.Mesh
    Floor_Floor_0: THREE.Mesh
    Walls_Glass_0: THREE.Mesh
    Walls_Light_0: THREE.Mesh
    Walls_Metal_0_4: THREE.Mesh
    Walls_Walls_0: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
    PaletteMaterial003: THREE.MeshStandardMaterial
    PaletteMaterial004: THREE.MeshStandardMaterial
    PaletteMaterial005: THREE.MeshStandardMaterial
    PaletteMaterial006: THREE.MeshStandardMaterial
  }
}

export function ScifiGallery(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/sci-fi-interior-gallery-10.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      {/* Lost floor frame */}
      {/* <mesh geometry={nodes.ScreenFrame_ScreenFrame_0.geometry} material={materials.PaletteMaterial001} position={[0, 0.048, 0.127]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} /> */}
      <mesh geometry={nodes.Floor_Floor_0.geometry} material={materials.PaletteMaterial002} position={[0, 0.009, 0.127]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Walls_Glass_0.geometry} material={materials.PaletteMaterial003} position={[0, 0.089, 0.128]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Walls_Light_0.geometry} material={materials.PaletteMaterial004} position={[0, 0.089, 0.128]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Walls_Metal_0_4.geometry} material={materials.PaletteMaterial005} position={[0, 0.089, 0.128]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Walls_Walls_0.geometry} material={materials.PaletteMaterial006} position={[0, 0.089, 0.128]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/models/sci-fi-interior-gallery-10.glb')
