/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/venue_stage_for_great_events.glb --types 
Author: QuarizonStudio (https://sketchfab.com/QuarizonStudio)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/venue-stage-for-great-events-d74b3baa5a74430fb3717cfa3d883476
Title: venue stage for great events
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    house_house_0: THREE.Mesh
    wall_wall1_0: THREE.Mesh
    wall_wall2_0: THREE.Mesh
    stage_stage3_0: THREE.Mesh
    stage_stage1_0: THREE.Mesh
    stage_stage2_0: THREE.Mesh
    backwall_backwall4_0: THREE.Mesh
    backwall_backwall1_0: THREE.Mesh
    backwall_backwall3_0: THREE.Mesh
    backwall_backwall5_0: THREE.Mesh
    backwall_backwall2_0: THREE.Mesh
    backwall_backwall6_0: THREE.Mesh
    screen1_screen1_0: THREE.Mesh
    light_light1_0: THREE.Mesh
    light_light2_0: THREE.Mesh
    dec_dec1_0: THREE.Mesh
    dec_dec2_0: THREE.Mesh
    spot2_spot2a_0: THREE.Mesh
    spot2_spot2b_0: THREE.Mesh
    seat_seat_0: THREE.Mesh
    seat_seat_0_1: THREE.Mesh
    seat_seat_0_2: THREE.Mesh
    seat_seat_0_3: THREE.Mesh
    seat_seat_0_4: THREE.Mesh
    screen2_screen2_0: THREE.Mesh
    plant_plant_0: THREE.Mesh
    silver_frame_silver_frame_0: THREE.Mesh
    silver_frame_silver_frame_0_1: THREE.Mesh
    spot1_spot1a_0: THREE.Mesh
    spot1_spot1b_0: THREE.Mesh
  }
  materials: {
    house: THREE.MeshStandardMaterial
    wall1: THREE.MeshStandardMaterial
    wall2: THREE.MeshStandardMaterial
    stage3: THREE.MeshStandardMaterial
    stage1: THREE.MeshStandardMaterial
    stage2: THREE.MeshStandardMaterial
    backwall4: THREE.MeshStandardMaterial
    backwall1: THREE.MeshStandardMaterial
    backwall3: THREE.MeshStandardMaterial
    backwall5: THREE.MeshStandardMaterial
    backwall2: THREE.MeshStandardMaterial
    backwall6: THREE.MeshStandardMaterial
    screen1: THREE.MeshStandardMaterial
    light1: THREE.MeshStandardMaterial
    light2: THREE.MeshStandardMaterial
    dec1: THREE.MeshStandardMaterial
    dec2: THREE.MeshStandardMaterial
    spot2a: THREE.MeshStandardMaterial
    spot2b: THREE.MeshStandardMaterial
    seat: THREE.MeshStandardMaterial
    screen2: THREE.MeshStandardMaterial
    plant: THREE.MeshStandardMaterial
    silver_frame: THREE.MeshStandardMaterial
    spot1a: THREE.MeshStandardMaterial
    spot1b: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Stage(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/venue_stage_for_great_events.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.wall_wall1_0.geometry} material={materials.wall1} />
          <mesh geometry={nodes.wall_wall2_0.geometry} material={materials.wall2} />
        </group>
        <group position={[0, 40.763, -322.971]} rotation={[-Math.PI / 2, 0, 0]} scale={[2087.827, 713.238, 41.23]}>
          <mesh geometry={nodes.stage_stage3_0.geometry} material={materials.stage3} />
          <mesh geometry={nodes.stage_stage1_0.geometry} material={materials.stage1} />
          <mesh geometry={nodes.stage_stage2_0.geometry} material={materials.stage2} />
        </group>
        <group position={[0, 78.35, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.backwall_backwall4_0.geometry} material={materials.backwall4} />
          <mesh geometry={nodes.backwall_backwall1_0.geometry} material={materials.backwall1} />
          <mesh geometry={nodes.backwall_backwall3_0.geometry} material={materials.backwall3} />
          <mesh geometry={nodes.backwall_backwall5_0.geometry} material={materials.backwall5} />
          <mesh geometry={nodes.backwall_backwall2_0.geometry} material={materials.backwall2} />
          <mesh geometry={nodes.backwall_backwall6_0.geometry} material={materials.backwall6} />
        </group>
        <group position={[-1716.001, 839.368, -230.078]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 15.726]}>
          <mesh geometry={nodes.light_light1_0.geometry} material={materials.light1} />
          <mesh geometry={nodes.light_light2_0.geometry} material={materials.light2} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.dec_dec1_0.geometry} material={materials.dec1} />
          <mesh geometry={nodes.dec_dec2_0.geometry} material={materials.dec2} />
        </group>
        <group position={[23.072, -100.61, 2953.393]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100}>
          <mesh geometry={nodes.spot2_spot2a_0.geometry} material={materials.spot2a} />
          <mesh geometry={nodes.spot2_spot2b_0.geometry} material={materials.spot2b} />
        </group>
        <group position={[-139.669, 22.472, 916.236]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.seat_seat_0.geometry} material={materials.seat} />
          <mesh geometry={nodes.seat_seat_0_1.geometry} material={materials.seat} />
          <mesh geometry={nodes.seat_seat_0_2.geometry} material={materials.seat} />
          <mesh geometry={nodes.seat_seat_0_3.geometry} material={materials.seat} />
          <mesh geometry={nodes.seat_seat_0_4.geometry} material={materials.seat} />
        </group>
        <group position={[0, -32.803, -344.664]} rotation={[-Math.PI / 2, 0, 0]} scale={75.125}>
          <mesh geometry={nodes.silver_frame_silver_frame_0.geometry} material={materials.silver_frame} />
          <mesh geometry={nodes.silver_frame_silver_frame_0_1.geometry} material={materials.silver_frame} />
        </group>
        <group position={[0, -32.803, -344.664]} rotation={[-Math.PI / 2, 0, 0]} scale={75.125}>
          <mesh geometry={nodes.spot1_spot1a_0.geometry} material={materials.spot1a} />
          <mesh geometry={nodes.spot1_spot1b_0.geometry} material={materials.spot1b} />
        </group>
        <mesh geometry={nodes.house_house_0.geometry} material={materials.house} position={[0, 535.806, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[3699.588, 2374.425, 536.399]} />
        <mesh geometry={nodes.screen1_screen1_0.geometry} material={materials.screen1} position={[0, 122.369, -1074.066]} rotation={[-Math.PI / 2, 0, 0]} scale={[1278.599, 25.094, 41.23]} />
        <mesh geometry={nodes.screen2_screen2_0.geometry} material={materials.screen2} position={[2127.661, 269.9, -498.132]} rotation={[-Math.PI / 2, 0, 0]} scale={[52.544, 52.544, 39.788]} />
        <mesh geometry={nodes.plant_plant_0.geometry} material={materials.plant} position={[963.995, 75.672, -988.265]} rotation={[Math.PI, 0.626, -Math.PI]} scale={[60.897, 62.308, 59.578]} />
      </group>
    </group>
  )
}

useGLTF.preload('/venue_stage_for_great_events.glb')
