/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/virtual_store_cute_pastelle.glb --types 
Author: Shayan (https://sketchfab.com/mshayan02)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/virtual-store-cute-pastelle-953f0f8517eb4af1b1ba5bf85601f7dd
Title: Virtual Store Cute Pastelle
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_8: THREE.Mesh
    Object_9: THREE.Mesh
    Object_11: THREE.Mesh
    Object_12: THREE.Mesh
    Object_13: THREE.Mesh
    Object_15: THREE.Mesh
    Object_17: THREE.Mesh
    Object_19: THREE.Mesh
    Object_20: THREE.Mesh
    Object_22: THREE.Mesh
    Object_23: THREE.Mesh
    Object_24: THREE.Mesh
    Object_26: THREE.Mesh
    Object_27: THREE.Mesh
    Object_28: THREE.Mesh
    Object_29: THREE.Mesh
    Object_31: THREE.Mesh
    Object_32: THREE.Mesh
    Object_33: THREE.Mesh
    Object_34: THREE.Mesh
    Object_35: THREE.Mesh
    Object_37: THREE.Mesh
    Object_38: THREE.Mesh
    Object_40: THREE.Mesh
    Object_42: THREE.Mesh
    Object_43: THREE.Mesh
    Object_45: THREE.Mesh
    Object_46: THREE.Mesh
    Object_48: THREE.Mesh
    Object_50: THREE.Mesh
    Object_51: THREE.Mesh
    Object_53: THREE.Mesh
    Object_54: THREE.Mesh
    Object_56: THREE.Mesh
    Object_57: THREE.Mesh
    Object_59: THREE.Mesh
    Object_60: THREE.Mesh
    Object_62: THREE.Mesh
    Object_63: THREE.Mesh
    Object_64: THREE.Mesh
    Object_66: THREE.Mesh
    Object_67: THREE.Mesh
    Object_69: THREE.Mesh
    Object_70: THREE.Mesh
    Object_72: THREE.Mesh
    Object_73: THREE.Mesh
    Object_74: THREE.Mesh
    Object_76: THREE.Mesh
    Object_77: THREE.Mesh
    Object_79: THREE.Mesh
    Object_80: THREE.Mesh
    Object_82: THREE.Mesh
    Object_83: THREE.Mesh
    Object_85: THREE.Mesh
    Object_86: THREE.Mesh
    Object_88: THREE.Mesh
    Object_89: THREE.Mesh
    Object_91: THREE.Mesh
    Object_92: THREE.Mesh
    Object_93: THREE.Mesh
    Object_94: THREE.Mesh
    Object_96: THREE.Mesh
    Object_98: THREE.Mesh
    Object_100: THREE.Mesh
    Object_101: THREE.Mesh
    Object_102: THREE.Mesh
    Object_104: THREE.Mesh
    Object_105: THREE.Mesh
    Object_106: THREE.Mesh
    Object_107: THREE.Mesh
    Object_109: THREE.Mesh
    Object_111: THREE.Mesh
    Object_112: THREE.Mesh
    Object_114: THREE.Mesh
    Object_115: THREE.Mesh
    Object_117: THREE.Mesh
    Object_118: THREE.Mesh
    Object_120: THREE.Mesh
    Object_121: THREE.Mesh
    Object_122: THREE.Mesh
    Object_123: THREE.Mesh
    Object_125: THREE.Mesh
    Object_126: THREE.Mesh
    Object_127: THREE.Mesh
    Object_128: THREE.Mesh
    Object_130: THREE.Mesh
    Object_131: THREE.Mesh
    Object_132: THREE.Mesh
    Object_133: THREE.Mesh
    Object_135: THREE.Mesh
    Object_136: THREE.Mesh
    Object_137: THREE.Mesh
    Object_138: THREE.Mesh
    Object_140: THREE.Mesh
    Object_141: THREE.Mesh
    Object_142: THREE.Mesh
    Object_144: THREE.Mesh
    Object_145: THREE.Mesh
    Object_146: THREE.Mesh
    Object_148: THREE.Mesh
    Object_149: THREE.Mesh
    Object_151: THREE.Mesh
    Object_152: THREE.Mesh
    Object_153: THREE.Mesh
    Object_154: THREE.Mesh
    Object_156: THREE.Mesh
    Object_157: THREE.Mesh
    Object_158: THREE.Mesh
    Object_159: THREE.Mesh
    Object_161: THREE.Mesh
    Object_162: THREE.Mesh
    Object_163: THREE.Mesh
    Object_164: THREE.Mesh
    Object_166: THREE.Mesh
    Object_167: THREE.Mesh
    Object_169: THREE.Mesh
    Object_170: THREE.Mesh
    Object_172: THREE.Mesh
    Object_173: THREE.Mesh
    Object_175: THREE.Mesh
    Object_176: THREE.Mesh
    Object_178: THREE.Mesh
    Object_179: THREE.Mesh
    Object_181: THREE.Mesh
    Object_182: THREE.Mesh
    Object_183: THREE.Mesh
    Object_185: THREE.Mesh
    Object_186: THREE.Mesh
    Object_188: THREE.Mesh
    Object_189: THREE.Mesh
    Object_190: THREE.Mesh
    Object_191: THREE.Mesh
    Object_193: THREE.Mesh
    Object_194: THREE.Mesh
    Object_195: THREE.Mesh
    Object_196: THREE.Mesh
    Object_198: THREE.Mesh
    Object_199: THREE.Mesh
    Object_200: THREE.Mesh
    Object_202: THREE.Mesh
    Object_203: THREE.Mesh
    Object_204: THREE.Mesh
    Object_206: THREE.Mesh
    Object_207: THREE.Mesh
    Object_208: THREE.Mesh
  }
  materials: {
    granular_concrete: THREE.MeshStandardMaterial
    laminate_floor: THREE.MeshStandardMaterial
    Pink_Matt: THREE.MeshStandardMaterial
    Black_Matt: THREE.MeshStandardMaterial
    Light_50_quarter_Bright: THREE.MeshStandardMaterial
    Pink_Matt_0: THREE.MeshStandardMaterial
    Ascent_Color: THREE.MeshStandardMaterial
    Light_230_Semi_Bright: THREE.MeshStandardMaterial
    Black_Matt_0: THREE.MeshStandardMaterial
    Matt_Wood: THREE.MeshStandardMaterial
    Matt_Wood_Dark: THREE.MeshStandardMaterial
    Light_50_quarter_Bright_0: THREE.MeshStandardMaterial
    White_Matt: THREE.MeshStandardMaterial
    beige_wall_001: THREE.MeshStandardMaterial
    Ascent_Color_0: THREE.MeshStandardMaterial
    Mirror: THREE.MeshStandardMaterial
    granular_concrete_0: THREE.MeshStandardMaterial
    beige_wall_001_0: THREE.MeshStandardMaterial
    Light_10_Dim: THREE.MeshStandardMaterial
    Bronze: THREE.MeshStandardMaterial
    Glass: THREE.MeshPhysicalMaterial
    Light_Warm: THREE.MeshStandardMaterial
    material_0: THREE.MeshStandardMaterial
    Light_230_Semi_Bright_0: THREE.MeshStandardMaterial
    laminate_floor_0: THREE.MeshStandardMaterial
    Cushion: THREE.MeshStandardMaterial
    Light_1600_Bright: THREE.MeshStandardMaterial
  }
}

export function Store(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/virtual_store_cute_pastelle.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-6.96, 3.262, 5.059]}>
        <mesh geometry={nodes.Object_8.geometry} material={materials.Black_Matt} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Light_50_quarter_Bright} />
      </group>
      <group position={[-8.626, 0.438, 0.702]}>
        <mesh geometry={nodes.Object_11.geometry} material={materials.Pink_Matt_0} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.Ascent_Color} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.Light_230_Semi_Bright} />
      </group>
      {/* <group position={[-0.008, 0, 0.011]}>
        <mesh geometry={nodes.Object_42.geometry} material={materials.Mirror} />
        <mesh geometry={nodes.Object_43.geometry} material={materials.Ascent_Color} />
      </group> */}
      <group position={[0.229, 0, -0.045]}>
        <mesh geometry={nodes.Object_56.geometry} material={materials.Black_Matt_0} />
        <mesh geometry={nodes.Object_57.geometry} material={materials.Ascent_Color} />
      </group>
      <group position={[-9.625, -0.04, 0]}>
        <mesh geometry={nodes.Object_66.geometry} material={materials.Black_Matt} />
        <mesh geometry={nodes.Object_67.geometry} material={materials.Light_50_quarter_Bright} />
      </group>
      <group position={[-5.058, 5.484, 4.249]} scale={0.05}>
        <mesh geometry={nodes.Object_72.geometry} material={materials.Light_10_Dim} />
        <mesh geometry={nodes.Object_73.geometry} material={materials.Black_Matt_0} />
        <mesh geometry={nodes.Object_74.geometry} material={materials.Bronze} />
      </group>
      <group position={[6.623, 4.469, -5.275]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.113}>
        <mesh geometry={nodes.Object_76.geometry} material={materials.Light_10_Dim} />
        <mesh geometry={nodes.Object_77.geometry} material={materials.Black_Matt_0} />
      </group>
      <group position={[6.077, 5.043, 4.05]} scale={[0.703, 0.509, 0.703]}>
        <mesh geometry={nodes.Object_79.geometry} material={materials.Light_10_Dim} />
        <mesh geometry={nodes.Object_80.geometry} material={materials.Black_Matt_0} />
      </group>
      <group position={[0, 4.244, 4.358]} scale={0.077}>
        <mesh geometry={nodes.Object_82.geometry} material={materials.Black_Matt_0} />
        <mesh geometry={nodes.Object_83.geometry} material={materials.Light_10_Dim} />
      </group>
      <group position={[-7.483, 3.62, 1.014]}>
        <mesh geometry={nodes.Object_85.geometry} material={materials.Black_Matt} />
        <mesh geometry={nodes.Object_86.geometry} material={materials.Light_50_quarter_Bright} />
      </group>
      <group position={[-8.837, 1.305, -4.732]} rotation={[-Math.PI, -0.79, -Math.PI]} scale={0.422}>
        <mesh geometry={nodes.Object_88.geometry} material={materials.Pink_Matt_0} />
        <mesh geometry={nodes.Object_89.geometry} material={materials.Light_10_Dim} />
      </group>
      <group position={[-2.464, 2.116, -6.528]} scale={0.075}>
        <mesh geometry={nodes.Object_91.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Object_92.geometry} material={materials.Bronze} />
        <mesh geometry={nodes.Object_93.geometry} material={materials.Light_Warm} />
        <mesh geometry={nodes.Object_94.geometry} material={materials.Black_Matt_0} />
      </group>
      <group position={[-7.307, 2.751, -6.138]} scale={0.075}>
        <mesh geometry={nodes.Object_104.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Object_105.geometry} material={materials.Bronze} />
        <mesh geometry={nodes.Object_106.geometry} material={materials.Light_Warm} />
        <mesh geometry={nodes.Object_107.geometry} material={materials.Black_Matt_0} />
      </group>
      <group position={[0, 0, -1.555]}>
        <mesh geometry={nodes.Object_114.geometry} material={materials.Matt_Wood} />
        <mesh geometry={nodes.Object_115.geometry} material={materials.Ascent_Color} />
      </group>
      <group position={[6.228, 0.001, 4.36]} rotation={[0, 1.112, 0]} scale={[0.454, 0.671, 0.454]}>
        <mesh geometry={nodes.Object_117.geometry} material={materials.Pink_Matt_0} />
        <mesh geometry={nodes.Object_118.geometry} material={materials.Ascent_Color} />
      </group>
      <group position={[4.302, 0, -5.687]} rotation={[0, Math.PI / 2, 0]} scale={1.118}>
        <mesh geometry={nodes.Object_120.geometry} material={materials.Black_Matt_0} />
        <mesh geometry={nodes.Object_121.geometry} material={materials.Mirror} />
        <mesh geometry={nodes.Object_122.geometry} material={materials.Light_230_Semi_Bright} />
        <mesh geometry={nodes.Object_123.geometry} material={materials.Ascent_Color} />
      </group>
      <group position={[-0.217, 0.005, 2.109]}>
        <mesh geometry={nodes.Object_125.geometry} material={materials.laminate_floor_0} />
        <mesh geometry={nodes.Object_126.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Object_127.geometry} material={materials.beige_wall_001_0} />
        <mesh geometry={nodes.Object_128.geometry} material={materials.Light_50_quarter_Bright_0} />
      </group>
      <group position={[-0.954, 0, 5.22]} rotation={[0, -0.105, 0]} scale={1.149}>
        <mesh geometry={nodes.Object_130.geometry} material={materials.Matt_Wood} />
        <mesh geometry={nodes.Object_131.geometry} material={materials.Light_50_quarter_Bright_0} />
        <mesh geometry={nodes.Object_132.geometry} material={materials.Black_Matt_0} />
        <mesh geometry={nodes.Object_133.geometry} material={materials.Cushion} />
      </group>
      <group position={[-2.71, 0, 5.601]} rotation={[0, Math.PI / 2, 0]} scale={1.149}>
        <mesh geometry={nodes.Object_135.geometry} material={materials.Matt_Wood} />
        <mesh geometry={nodes.Object_136.geometry} material={materials.Light_50_quarter_Bright_0} />
        <mesh geometry={nodes.Object_137.geometry} material={materials.Black_Matt_0} />
        <mesh geometry={nodes.Object_138.geometry} material={materials.Cushion} />
      </group>
      <group position={[-6.278, -0.239, 5.217]}>
        <mesh geometry={nodes.Object_140.geometry} material={materials.beige_wall_001_0} />
        <mesh geometry={nodes.Object_141.geometry} material={materials.Ascent_Color} />
        <mesh geometry={nodes.Object_142.geometry} material={materials.Black_Matt_0} />
      </group>
      <group position={[7.798, 0, 4.861]} rotation={[0, -Math.PI / 2, 0]} scale={[1.853, 1.089, 0.837]}>
        <mesh geometry={nodes.Object_144.geometry} material={materials.Black_Matt_0} />
        <mesh geometry={nodes.Object_145.geometry} material={materials.Light_50_quarter_Bright_0} />
        <mesh geometry={nodes.Object_146.geometry} material={materials.Ascent_Color} />
      </group>
      <group position={[0.123, -0.047, -2.032]} scale={[1, 1, 1.126]}>
        <mesh geometry={nodes.Object_148.geometry} material={materials.Black_Matt_0} />
        <mesh geometry={nodes.Object_149.geometry} material={materials.Ascent_Color} />
      </group>
      <group position={[7.491, 0.001, -5.486]} rotation={[0, -0.105, 0]} scale={1.149}>
        <mesh geometry={nodes.Object_151.geometry} material={materials.Matt_Wood} />
        <mesh geometry={nodes.Object_152.geometry} material={materials.Light_50_quarter_Bright_0} />
        <mesh geometry={nodes.Object_153.geometry} material={materials.Black_Matt_0} />
        <mesh geometry={nodes.Object_154.geometry} material={materials.Cushion} />
      </group>
      <group position={[0.018, 0, 5.226]} rotation={[0, 0.001, 0]} scale={1.149}>
        <mesh geometry={nodes.Object_156.geometry} material={materials.Matt_Wood} />
        <mesh geometry={nodes.Object_157.geometry} material={materials.Light_50_quarter_Bright_0} />
        <mesh geometry={nodes.Object_158.geometry} material={materials.Black_Matt_0} />
        <mesh geometry={nodes.Object_159.geometry} material={materials.Cushion} />
      </group>
      <group position={[1.248, 0, 5.201]} rotation={[0, 0.421, 0]} scale={1.149}>
        <mesh geometry={nodes.Object_161.geometry} material={materials.Matt_Wood} />
        <mesh geometry={nodes.Object_162.geometry} material={materials.Light_50_quarter_Bright_0} />
        <mesh geometry={nodes.Object_163.geometry} material={materials.Black_Matt_0} />
        <mesh geometry={nodes.Object_164.geometry} material={materials.Cushion} />
      </group>
      <group position={[-2.318, 0.001, 1.17]} rotation={[0, 1.112, 0]} scale={[0.454, 0.671, 0.454]}>
        <mesh geometry={nodes.Object_166.geometry} material={materials.Pink_Matt_0} />
        <mesh geometry={nodes.Object_167.geometry} material={materials.Ascent_Color} />
      </group>
      <group position={[3.361, 0.001, 1.17]} rotation={[0, 1.112, 0]} scale={[0.454, 0.671, 0.454]}>
        <mesh geometry={nodes.Object_169.geometry} material={materials.Pink_Matt_0} />
        <mesh geometry={nodes.Object_170.geometry} material={materials.Ascent_Color} />
      </group>
      <group position={[2.721, 0.001, -5.257]} rotation={[0, 1.112, 0]} scale={[0.454, 0.671, 0.454]}>
        <mesh geometry={nodes.Object_172.geometry} material={materials.Pink_Matt_0} />
        <mesh geometry={nodes.Object_173.geometry} material={materials.Ascent_Color} />
      </group>
      <group position={[-2.463, 0.001, -5.257]} rotation={[0, 1.112, 0]} scale={[0.454, 0.671, 0.454]}>
        <mesh geometry={nodes.Object_175.geometry} material={materials.Pink_Matt_0} />
        <mesh geometry={nodes.Object_176.geometry} material={materials.Ascent_Color} />
      </group>
      <group position={[0.001, 0.001, -5.257]} rotation={[0, 1.112, 0]} scale={[0.454, 0.671, 0.454]}>
        <mesh geometry={nodes.Object_178.geometry} material={materials.Pink_Matt_0} />
        <mesh geometry={nodes.Object_179.geometry} material={materials.Ascent_Color} />
      </group>
      <group position={[-6.278, 1.165, 5.217]}>
        <mesh geometry={nodes.Object_181.geometry} material={materials.beige_wall_001_0} />
        <mesh geometry={nodes.Object_182.geometry} material={materials.Ascent_Color} />
        <mesh geometry={nodes.Object_183.geometry} material={materials.Black_Matt_0} />
      </group>
      <group position={[-1.355, 2.899, 2.719]}>
        <mesh geometry={nodes.Object_185.geometry} material={materials.Black_Matt_0} />
        <mesh geometry={nodes.Object_186.geometry} material={materials.Light_1600_Bright} />
      </group>
      <group position={[1.119, -0.056, 5.965]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh geometry={nodes.Object_188.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Object_189.geometry} material={materials.beige_wall_001_0} />
        <mesh geometry={nodes.Object_190.geometry} material={materials.Light_10_Dim} />
        <mesh geometry={nodes.Object_191.geometry} material={materials.Ascent_Color} />
      </group>
      <group position={[-1.115, -0.056, 5.965]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh geometry={nodes.Object_193.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Object_194.geometry} material={materials.beige_wall_001_0} />
        <mesh geometry={nodes.Object_195.geometry} material={materials.Light_10_Dim} />
        <mesh geometry={nodes.Object_196.geometry} material={materials.Ascent_Color} />
      </group>
      <group position={[0.004, 0, 3.742]}>
        <mesh geometry={nodes.Object_198.geometry} material={materials.Pink_Matt_0} />
        <mesh geometry={nodes.Object_199.geometry} material={materials.Matt_Wood} />
        <mesh geometry={nodes.Object_200.geometry} material={materials.Ascent_Color} />
      </group>
      <group position={[6.437, 0, 1.208]}>
        <mesh geometry={nodes.Object_202.geometry} material={materials.Pink_Matt} />
        <mesh geometry={nodes.Object_203.geometry} material={materials.Ascent_Color_0} />
        <mesh geometry={nodes.Object_204.geometry} material={materials.Light_50_quarter_Bright} />
      </group>
      <group position={[-5.791, 0, 1.208]}>
        <mesh geometry={nodes.Object_206.geometry} material={materials.Pink_Matt} />
        <mesh geometry={nodes.Object_207.geometry} material={materials.Ascent_Color_0} />
        <mesh geometry={nodes.Object_208.geometry} material={materials.Light_50_quarter_Bright} />
      </group>
      <mesh geometry={nodes.Object_4.geometry} material={materials.granular_concrete} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.laminate_floor} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.Pink_Matt} />
      <mesh geometry={nodes.Object_15.geometry} material={materials.Pink_Matt_0} />
      <mesh geometry={nodes.Object_17.geometry} material={materials.Black_Matt_0} />
      <mesh geometry={nodes.Object_19.geometry} material={materials.Matt_Wood} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.Matt_Wood_Dark} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.Matt_Wood} />
      <mesh geometry={nodes.Object_23.geometry} material={materials.Light_50_quarter_Bright_0} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.Matt_Wood_Dark} />
      <mesh geometry={nodes.Object_26.geometry} material={materials.White_Matt} />
      <mesh geometry={nodes.Object_27.geometry} material={materials.Pink_Matt_0} />
      <mesh geometry={nodes.Object_28.geometry} material={materials.Light_50_quarter_Bright_0} />
      <mesh geometry={nodes.Object_29.geometry} material={materials.Ascent_Color} />
      <mesh geometry={nodes.Object_31.geometry} material={materials.granular_concrete} />
      <mesh geometry={nodes.Object_32.geometry} material={materials.laminate_floor} />
      <mesh geometry={nodes.Object_33.geometry} material={materials.beige_wall_001} />
      <mesh geometry={nodes.Object_34.geometry} material={materials.Black_Matt} />
      <mesh geometry={nodes.Object_35.geometry} material={materials.beige_wall_001} />
      <mesh geometry={nodes.Object_37.geometry} material={materials.Ascent_Color_0} />
      <mesh geometry={nodes.Object_38.geometry} material={materials.Light_50_quarter_Bright} />
      <mesh geometry={nodes.Object_40.geometry} material={materials.granular_concrete} />
      <mesh geometry={nodes.Object_45.geometry} material={materials.Pink_Matt_0} />
      <mesh geometry={nodes.Object_46.geometry} material={materials.Ascent_Color} />
      <mesh geometry={nodes.Object_48.geometry} material={materials.granular_concrete} />
      <mesh geometry={nodes.Object_50.geometry} material={materials.granular_concrete_0} />
      <mesh geometry={nodes.Object_51.geometry} material={materials.beige_wall_001_0} />
      <mesh geometry={nodes.Object_53.geometry} material={materials.Black_Matt_0} />
      <mesh geometry={nodes.Object_54.geometry} material={materials.Light_50_quarter_Bright_0} />
      <mesh geometry={nodes.Object_59.geometry} material={materials.granular_concrete} />
      <mesh geometry={nodes.Object_60.geometry} material={materials.beige_wall_001} />
      <mesh geometry={nodes.Object_62.geometry} material={materials.Black_Matt_0} />
      <mesh geometry={nodes.Object_63.geometry} material={materials.Ascent_Color} />
      <mesh geometry={nodes.Object_64.geometry} material={materials.Light_50_quarter_Bright_0} />
      <mesh geometry={nodes.Object_69.geometry} material={materials.Pink_Matt} />
      <mesh geometry={nodes.Object_70.geometry} material={materials.beige_wall_001} />
      <mesh geometry={nodes.Object_96.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_98.geometry} material={materials.Pink_Matt_0} />
      <mesh geometry={nodes.Object_100.geometry} material={materials.Black_Matt} />
      <mesh geometry={nodes.Object_101.geometry} material={materials.Light_230_Semi_Bright_0} />
      <mesh geometry={nodes.Object_102.geometry} material={materials.Ascent_Color_0} />
      <mesh geometry={nodes.Object_109.geometry} material={materials.Pink_Matt} position={[-8.626, 0.438, 0.702]} />
      <mesh geometry={nodes.Object_111.geometry} material={materials.beige_wall_001_0} />
      <mesh geometry={nodes.Object_112.geometry} material={materials.beige_wall_001_0} />
    </group>
  )
}

useGLTF.preload('/models/virtual_store_cute_pastelle.glb')
